# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import smscash_pb2 as smscash__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in smscash_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimcashStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authorize = channel.unary_unary(
                '/smscash.Simcash/Authorize',
                request_serializer=smscash__pb2.AuthorizeRequest.SerializeToString,
                response_deserializer=smscash__pb2.AuthorizeResponse.FromString,
                _registered_method=True)
        self.Recoverpassword = channel.unary_unary(
                '/smscash.Simcash/Recoverpassword',
                request_serializer=smscash__pb2.MessageRequest.SerializeToString,
                response_deserializer=smscash__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.Recoverpasswordverify = channel.unary_unary(
                '/smscash.Simcash/Recoverpasswordverify',
                request_serializer=smscash__pb2.MessageRequest.SerializeToString,
                response_deserializer=smscash__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.Changepassword = channel.unary_unary(
                '/smscash.Simcash/Changepassword',
                request_serializer=smscash__pb2.MessageRequest.SerializeToString,
                response_deserializer=smscash__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/smscash.Simcash/Register',
                request_serializer=smscash__pb2.MessageRequest.SerializeToString,
                response_deserializer=smscash__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.Registerverify = channel.unary_unary(
                '/smscash.Simcash/Registerverify',
                request_serializer=smscash__pb2.MessageRequest.SerializeToString,
                response_deserializer=smscash__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.Openchannel = channel.stream_stream(
                '/smscash.Simcash/Openchannel',
                request_serializer=smscash__pb2.MessageRequest.SerializeToString,
                response_deserializer=smscash__pb2.MessageResponse.FromString,
                _registered_method=True)


class SimcashServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Authorize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recoverpassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recoverpasswordverify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Changepassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Registerverify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Openchannel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimcashServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authorize': grpc.unary_unary_rpc_method_handler(
                    servicer.Authorize,
                    request_deserializer=smscash__pb2.AuthorizeRequest.FromString,
                    response_serializer=smscash__pb2.AuthorizeResponse.SerializeToString,
            ),
            'Recoverpassword': grpc.unary_unary_rpc_method_handler(
                    servicer.Recoverpassword,
                    request_deserializer=smscash__pb2.MessageRequest.FromString,
                    response_serializer=smscash__pb2.MessageResponse.SerializeToString,
            ),
            'Recoverpasswordverify': grpc.unary_unary_rpc_method_handler(
                    servicer.Recoverpasswordverify,
                    request_deserializer=smscash__pb2.MessageRequest.FromString,
                    response_serializer=smscash__pb2.MessageResponse.SerializeToString,
            ),
            'Changepassword': grpc.unary_unary_rpc_method_handler(
                    servicer.Changepassword,
                    request_deserializer=smscash__pb2.MessageRequest.FromString,
                    response_serializer=smscash__pb2.MessageResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=smscash__pb2.MessageRequest.FromString,
                    response_serializer=smscash__pb2.MessageResponse.SerializeToString,
            ),
            'Registerverify': grpc.unary_unary_rpc_method_handler(
                    servicer.Registerverify,
                    request_deserializer=smscash__pb2.MessageRequest.FromString,
                    response_serializer=smscash__pb2.MessageResponse.SerializeToString,
            ),
            'Openchannel': grpc.stream_stream_rpc_method_handler(
                    servicer.Openchannel,
                    request_deserializer=smscash__pb2.MessageRequest.FromString,
                    response_serializer=smscash__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smscash.Simcash', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smscash.Simcash', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Simcash(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Authorize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smscash.Simcash/Authorize',
            smscash__pb2.AuthorizeRequest.SerializeToString,
            smscash__pb2.AuthorizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recoverpassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smscash.Simcash/Recoverpassword',
            smscash__pb2.MessageRequest.SerializeToString,
            smscash__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recoverpasswordverify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smscash.Simcash/Recoverpasswordverify',
            smscash__pb2.MessageRequest.SerializeToString,
            smscash__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Changepassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smscash.Simcash/Changepassword',
            smscash__pb2.MessageRequest.SerializeToString,
            smscash__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smscash.Simcash/Register',
            smscash__pb2.MessageRequest.SerializeToString,
            smscash__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Registerverify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smscash.Simcash/Registerverify',
            smscash__pb2.MessageRequest.SerializeToString,
            smscash__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Openchannel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/smscash.Simcash/Openchannel',
            smscash__pb2.MessageRequest.SerializeToString,
            smscash__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
