# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: smscash.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'smscash.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsmscash.proto\x12\x07smscash\".\n\x0eMessageRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"/\n\x0fMessageResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"L\n\x10\x41uthorizeRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x17\n\x0f\x61\x64\x64itional_data\x18\x03 \x01(\t\"C\n\x11\x41uthorizeResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t2\xf0\x03\n\x07Simcash\x12\x42\n\tAuthorize\x12\x19.smscash.AuthorizeRequest\x1a\x1a.smscash.AuthorizeResponse\x12\x44\n\x0fRecoverpassword\x12\x17.smscash.MessageRequest\x1a\x18.smscash.MessageResponse\x12J\n\x15Recoverpasswordverify\x12\x17.smscash.MessageRequest\x1a\x18.smscash.MessageResponse\x12\x43\n\x0e\x43hangepassword\x12\x17.smscash.MessageRequest\x1a\x18.smscash.MessageResponse\x12=\n\x08Register\x12\x17.smscash.MessageRequest\x1a\x18.smscash.MessageResponse\x12\x43\n\x0eRegisterverify\x12\x17.smscash.MessageRequest\x1a\x18.smscash.MessageResponse\x12\x46\n\x0bOpenchannel\x12\x17.smscash.MessageRequest\x1a\x18.smscash.MessageResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smscash_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=26
  _globals['_MESSAGEREQUEST']._serialized_end=72
  _globals['_MESSAGERESPONSE']._serialized_start=74
  _globals['_MESSAGERESPONSE']._serialized_end=121
  _globals['_AUTHORIZEREQUEST']._serialized_start=123
  _globals['_AUTHORIZEREQUEST']._serialized_end=199
  _globals['_AUTHORIZERESPONSE']._serialized_start=201
  _globals['_AUTHORIZERESPONSE']._serialized_end=268
  _globals['_SIMCASH']._serialized_start=271
  _globals['_SIMCASH']._serialized_end=767
# @@protoc_insertion_point(module_scope)
